#!/bin/bash
# File: 0-transfer_file

# Check if the number of arguments is less than 4
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign variables to arguments
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Use scp with the provided parameters to transfer the file to the user's home directory
if scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"; then
    echo "File transferred successfully."
else
    echo "Error in transferring file."
fi
