#!/usr/bin/env bash
# script to ping ip addresses
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract IP address from the argument
ip_address="$1"

# Ping the IP address 5 times
ping -c 5 "$ip_address"
