#!/usr/bin/env bash
# FizzBuzz program

for counter in {1..100}
do
    if [ $((counter % 15)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((counter % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((counter % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo $counter

    fi
    ((counter++))
done
