#!/usr/bin/env bash
# print "Best School" ten times using while loop

counter=0
while [ $counter -lt 10 ]
do
    if [ $counter -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
