#!/usr/bin/env bash
# print numbers from 1 to 20 with specific messages for 4, 9 and 17

counter=1
while [ $counter -le 20 ]
do
    case $counter in
        4)
            echo $counter
            echo "bad luck from China"
            ;;
        9)
            echo $counter
            echo "bad luck from Japan"
            ;;
        17)
            echo $counter
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;  
    esac
    ((counter++))
done
